name: Sync to Hugging Face
on:
  push:
    branches: [fix]
  # อนุญาตให้กดรัน Manual ได้ด้วยเพื่อความสะดวก
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ntwkkm 
          SPACE_NAME: dev-shiny
        run: |
          # 1. ตั้งค่า Git User
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

          # 2. เพิ่ม Remote URL
          git remote add space https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME

          # 3. สั่ง Push (แก้ตรงนี้)
          # HEAD:main หมายถึง "เอา Code ปัจจุบัน (ไม่ว่าจะอยู่ branch ไหน) ไปยัดใส่ branch main ของ Hugging Face"
          git push --force space HEAD:main
